default:
  tags: 
  - docker
  image: python:3.7

before_script:
  - python --version
  - cd plugin
  - pip3 install -r requirements.txt

stages:
  - Static Analysis
  - Image
  - Test
  - Merge

pylint:
  stage: Static Analysis
  script:
  - cd ..
  - pylint -d C0301 plugin/*/*.py --rcfile  plugin/.pylintrc
  allow_failure: false

dockerhub:
  stage: Image
  tags:
    - shell

  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    
  script:
    - cd plugin
    - docker build -t txmm/engr300_redshield:testing .
    - docker push txmm/engr300_redshield:testing
  allow_failure: false


pytest:
  stage: Test
  image: txmm/engr300_redshield:testing
  script:
  - python3 -m pytest -vs
  allow_failure: false

merges:
  stage: Merge
  image: txmm/engr300_redshield:testing
  script:
  - python3 -m pytest -vs
  allow_failure: false
  only:
    - merge_requests

