# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
default:
  tags: 
  - docker
  image: python:3.7

before_script:
  - python --version
  - cd plugin
  - pip3 install -r requirements.txt

stages:
  - Static Analysis
  - Image
  - Test

pylint:
  stage: Static Analysis
  script:
  - cd ..
  - pylint -d C0301 plugin/*/*.py
  allow_failure: true

dockerhub:
  stage: Image
  tags:
    - shell

  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    
  script:
    - cd plugin
    - docker build -t txmm/engr300_redshield:testing .
    - docker push txmm/engr300_redshield:testing


pytest:
  stage: Test
  image: txmm/engr300_redshield:testing
  script:
  - echo diff
  - diff /builds/course-work/engr300/2021/group14/group-14/plugin/data/outputs/expected/analysis.txt /builds/course-work/engr300/2021/group14/group-14/plugin/data/outputs/actual/analysis.txt
  - python3 -m pytest -vs
