# image: gradle:alpine

stages:
  - Build
  - Test

build:
  stage: Build
  tags:
     - shell
  script:
    - echo "build"
  allow_failure: false

unit_testing:
  stage: Test
  tags:
     - shell
  script:
   - echo "test"
  allow_failure: false
